--smart-case
--type-set
asp=.aspx,.asx,.asp,.cshtml
--type-set
log=.log
--type-set
sass=.scss,.sass
--type-set
vim=.vim
--type-set
js=.js,.coffee
--type-set
web=.html,.js,.scss,.css,.php
--type-set
docs=.markdown,.md,.mdown,.rst,.txt
--ignore-dir=build/
